apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: basic-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: wschultz-boxboat/self-hosted-runner-tester
